name: Quality gates

on: [push]

defaults:
  run:
    working-directory: packages/backend

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: |
          yarn install --frozen-lockfile

    - name: Run Lint
      run: |
          yarn lint

    - name: Run feature tests
      run: |
          yarn features

    - name: Run integration tests
      run: |
          yarn test